### ISSUE TITLE
unable to connect to the cluster

### ISSUE THREAD

**Issue by zencircle** [aws-samples/row-estimator-for-apache-cassandra#1]
Unable to connect to the cluster 
```
root@py:/# python --version
Python 3.10.5

root@py:/# pip --version
pip 22.0.4 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)

/usr/local/bin/python -m pip install --upgrade pip

pip install row-estimator-for-apache-cassandra
pip install sortedcontainers
```
Log trace
```
cassandra-row-estimator --hostname cluster1-dc1-service.cass-operator --port 9042 --username $USER --password $PAS  \
 --keyspace system --table size_estimates --token-step 1 --dc dc1 --rows-per-request 1000
NFO:Endpoint: cluster1-dc2-service.cass-operator 9042
INFO:Keyspace name: system
INFO:Table name: size_estimates
INFO:Client SSL: None
INFO:Token step: 1
INFO:Limit of rows per token step: 1000
INFO:Pagination: 200
INFO:Execution-timeout: 360
ERROR:Closing connection <LibevConnection(139679763337936) 10.153.112.108:9042> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
ERROR:Closing connection <LibevConnection(139679739776880) 10.153.112.108:9042> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
ERROR:Closing connection <LibevConnection(139679495129888) 10.153.175.53:9042> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/row_estimator_for_apache_cassandra/estimator.py", line 242, in row_sampler
    results = session.execute(tbl_lookup_stmt, [val, next(it)])
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cassandra-row-estimator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/row_estimator_for_apache_cassandra/__main__.py", line 85, in main
    action_thread = Thread(target=estimator.row_sampler(json=False))
  File "/usr/local/lib/python3.10/site-packages/row_estimator_for_apache_cassandra/estimator.py", line 256, in row_sampler
    logger.info("no more token pairs")
NameError: name 'logger' is not defined
Exception ignored in atexit callback: <cyfunction _shutdown_clusters at 0x7f09bb050a00>
Traceback (most recent call last):
  File "cassandra/cluster.py", line 221, in cassandra.cluster._shutdown_clusters
  File "cassandra/cluster.py", line 1759, in cassandra.cluster.Cluster.shutdown
  File "cassandra/cluster.py", line 3147, in cassandra.cluster.Session.shutdown
  File "cassandra/pool.py", line 493, in cassandra.pool.HostConnection.shutdown
  File "/usr/local/lib/python3.10/site-packages/cassandra/io/libevreactor.py", line 296, in close
    ConnectionShutdown("Connection to %s was closed" % self.endpoint))
  File "cassandra/connection.py", line 214, in cassandra.connection.DefaultEndPoint.__str__
TypeError: %d format: a real number is required, not str
```

**Comment by zencircle** [comment]
From the same container cqlsh works
```
root@py:~# cqlsh --version
cqlsh 6.0.0
root@py:~# cqlsh cluster1-dc1-service.cass-operator -u $USER -p $PASS -e "SELECT * FROM system_schema.keyspaces"
 keyspace_name      | durable_writes | replication
--------------------+----------------+-------------------------------------------------------------------------------------------

        system_auth |           True | {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'dc1': '3', 'dc2': '5'}
      system_schema |           True |                                   {'class': 'org.apache.cassandra.locator.LocalStrategy'}
 system_distributed |           True |             {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'dc2': '5'}
             system |           True |                                   {'class': 'org.apache.cassandra.locator.LocalStrategy'}
      system_traces |           True |             {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'dc2': '5'}

(5 rows)

**Comment by nwheeler81** [comment]
@zencircle I think it's related to the python version>3.7+, there is a quick fix is to use Python 3.7.  
```
$ conda create --name py37 python=3.7
$ conda activate py37
$ pip install row-estimator-for-apache-cassandra sortedcontainers
$ cassandra-row-estimator --hostname "172.31.20.45" --port 9042 --keyspace ks_test_cql_replicator --table test_cql_replicator --token-step 4 --dc datacenter1 --json true
INFO:Endpoint: 172.31.20.45 9042
INFO:Keyspace name: ks_test_cql_replicator
INFO:Table name: test_cql_replicator
INFO:Client SSL: None
INFO:Token step: 4
INFO:Limit of rows per token step: 1000
INFO:Pagination: 200
INFO:Execution-timeout: 360
INFO:Number of sampled rows: 2000
INFO:Estimated size of a Cassandra JSON row
INFO:Mean: 337.70
INFO:Weighted_mean: 337.74
INFO:Median: 333.00
INFO:Min: 252
INFO:Max: 426
INFO:Average: 337.70
```

**Comment by zencircle** [comment]
```
root@centos ~]# conda create --name py37 python=3.7
Collecting package metadata (current_repodata.json): done
...
## Package Plan ##

  environment location: /opt/conda/envs/py37

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
    _openmp_mutex-5.1          |            1_gnu          21 KB
    ca-certificates-2022.4.26  |       h06a4308_0         124 KB
    certifi-2022.5.18.1        |   py37h06a4308_0         147 KB
    ld_impl_linux-64-2.38      |       h1181459_1         654 KB
    libffi-3.3                 |       he6710b0_2          50 KB
    libgcc-ng-11.2.0           |       h1234567_1         5.3 MB
    libgomp-11.2.0             |       h1234567_1         474 KB
    libstdcxx-ng-11.2.0        |       h1234567_1         4.7 MB
    ncurses-6.3                |       h7f8727e_2         782 KB
    openssl-1.1.1o             |       h7f8727e_0         2.5 MB
    pip-21.2.2                 |   py37h06a4308_0         1.8 MB
    python-3.7.13              |       h12debd9_0        46.2 MB
    readline-8.1.2             |       h7f8727e_1         354 KB
    setuptools-61.2.0          |   py37h06a4308_0        1007 KB
    sqlite-3.38.3              |       hc218d9a_0         1.0 MB
    tk-8.6.12                  |       h1ccaba5_0         3.0 MB
    wheel-0.37.1               |     pyhd3eb1b0_0          33 KB
    xz-5.2.5                   |       h7f8727e_1         339 KB
    zlib-1.2.12                |       h7f8727e_2         106 KB
    ------------------------------------------------------------
                                           Total:        68.6 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  ca-certificates    pkgs/main/linux-64::ca-certificates-2022.4.26-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2022.5.18.1-py37h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  ncurses            pkgs/main/linux-64::ncurses-6.3-h7f8727e_2
  openssl            pkgs/main/linux-64::openssl-1.1.1o-h7f8727e_0
  pip                pkgs/main/linux-64::pip-21.2.2-py37h06a4308_0
  python             pkgs/main/linux-64::python-3.7.13-h12debd9_0
  readline           pkgs/main/linux-64::readline-8.1.2-h7f8727e_1
  setuptools         pkgs/main/linux-64::setuptools-61.2.0-py37h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.38.3-hc218d9a_0
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7f8727e_1
  zlib               pkgs/main/linux-64::zlib-1.2.12-h7f8727e_2


Proceed ([y]/n)? y
...
[root@centos ~]# conda activate py37
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


[root@centos ~]# pip install row-estimator-for-apache-cassandra sortedcontainers
Collecting row-estimator-for-apache-cassandra
  Using cached row_estimator_for_apache_cassandra-0.0.3-py3-none-any.whl (14 kB)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting cassandra-driver
  Downloading cassandra_driver-3.25.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.7 MB)
     |████████████████████████████████| 3.7 MB 4.7 MB/s 
Collecting geomet<0.3,>=0.1
  Using cached geomet-0.2.1.post1-py3-none-any.whl (18 kB)
Collecting six>=1.9
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting click
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 8.2 MB/s 
Installing collected packages: six, click, geomet, cassandra-driver, sortedcontainers, row-estimator-for-apache-cassandra
Successfully installed cassandra-driver-3.25.0 click-8.1.3 geomet-0.2.1.post1 row-estimator-for-apache-cassandra-0.0.3 six-1.16.0 sortedcontainers-2.4.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[root@centos ~]# cassandra-row-estimator --hostname cluster1-dc1-service.cass-operator --port 9042 --username $USER --password $PASS  --keyspace system --table size_estimates --token-step 1 --dc dc1 --rows-per-request 1000
Traceback (most recent call last):
  File "/usr/local/bin/cassandra-row-estimator", line 7, in <module>
    from row_estimator_for_apache_cassandra.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/row_estimator_for_apache_cassandra/__main__.py", line 15, in <module>
    from importlib import resources  # Python 3.7+
ImportError: cannot import name 'resources'
```

**Comment by zencircle** [comment]
```
base) [root@centos /]# conda create --name py38 python=3.8
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /opt/conda/envs/py38

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2022.5.18.1        |   py38h06a4308_0         147 KB
    pip-21.2.4                 |   py38h06a4308_0         1.8 MB
    python-3.8.13              |       h12debd9_0        18.8 MB
    setuptools-61.2.0          |   py38h06a4308_0        1012 KB
    ------------------------------------------------------------
                                           Total:        21.7 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  ca-certificates    pkgs/main/linux-64::ca-certificates-2022.4.26-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2022.5.18.1-py38h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  ncurses            pkgs/main/linux-64::ncurses-6.3-h7f8727e_2
  openssl            pkgs/main/linux-64::openssl-1.1.1o-h7f8727e_0
  pip                pkgs/main/linux-64::pip-21.2.4-py38h06a4308_0
  python             pkgs/main/linux-64::python-3.8.13-h12debd9_0
  readline           pkgs/main/linux-64::readline-8.1.2-h7f8727e_1
  setuptools         pkgs/main/linux-64::setuptools-61.2.0-py38h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.38.3-hc218d9a_0
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7f8727e_1
  zlib               pkgs/main/linux-64::zlib-1.2.12-h7f8727e_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
setuptools-61.2.0    | 1012 KB   | ######################################################################################################################################################################### | 100% 
pip-21.2.4           | 1.8 MB    | ######################################################################################################################################################################### | 100% 
python-3.8.13        | 18.8 MB   | ######################################################################################################################################################################### | 100% 
certifi-2022.5.18.1  | 147 KB    | ######################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate py38
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) [root@centos /]# conda activate py38
(py38) [root@centos /]# pip install row-estimator-for-apache-cassandra sortedcontainers
Collecting row-estimator-for-apache-cassandra
  Using cached row_estimator_for_apache_cassandra-0.0.3-py3-none-any.whl (14 kB)
Collecting sortedcontainers
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting cassandra-driver
  Downloading cassandra_driver-3.25.0-cp38-cp38-manylinux1_x86_64.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 6.9 MB/s 
Collecting geomet<0.3,>=0.1
  Using cached geomet-0.2.1.post1-py3-none-any.whl (18 kB)
Collecting six>=1.9
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Installing collected packages: six, click, geomet, cassandra-driver, sortedcontainers, row-estimator-for-apache-cassandra
Successfully installed cassandra-driver-3.25.0 click-8.1.3 geomet-0.2.1.post1 row-estimator-for-apache-cassandra-0.0.3 six-1.16.0 sortedcontainers-2.4.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(py38) [root@centos /]# cassandra-row-estimator --hostname cluster1-dc1-service.cass-operator --port 9042 --username $USER --password $PASS  --keyspace system --table size_estimates --token-step 1 --dc dc1 --rows-per-request 1000 
INFO:Endpoint: cluster1-dc1-service.cass-operator 9042
INFO:Keyspace name: system
INFO:Table name: size_estimates
INFO:Client SSL: None
INFO:Token step: 1
INFO:Limit of rows per token step: 1000
INFO:Pagination: 200
INFO:Execution-timeout: 360
ERROR:Closing connection <LibevConnection(139716877180832) 10.153.136.64:9042> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
ERROR:Closing connection <LibevConnection(139716847053024) 10.153.129.93:9042> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
ERROR:Closing connection <LibevConnection(139716847373232) 10.153.186.22:9042> due to protocol error: Error from server: code=000a [Protocol error] message="Beta version of the protocol used (5/v5-beta), but USE_BETA flag is unset"
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/row_estimator_for_apache_cassandra/estimator.py", line 242, in row_sampler
    results = session.execute(tbl_lookup_stmt, [val, next(it)])
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/py38/bin/cassandra-row-estimator", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/row_estimator_for_apache_cassandra/__main__.py", line 85, in main
    action_thread = Thread(target=estimator.row_sampler(json=False))
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/row_estimator_for_apache_cassandra/estimator.py", line 256, in row_sampler
    logger.info("no more token pairs")
NameError: name 'logger' is not defined
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 221, in cassandra.cluster._shutdown_clusters
  File "cassandra/cluster.py", line 1759, in cassandra.cluster.Cluster.shutdown
  File "cassandra/cluster.py", line 3147, in cassandra.cluster.Session.shutdown
  File "cassandra/pool.py", line 493, in cassandra.pool.HostConnection.shutdown
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/cassandra/io/libevreactor.py", line 296, in close
    ConnectionShutdown("Connection to %s was closed" % self.endpoint))
  File "cassandra/connection.py", line 214, in cassandra.connection.DefaultEndPoint.__str__
TypeError: %d format: a number is required, not str
```

**Comment by zencircle** [comment]
```
cassandra@cqlsh> SHOW VERSION ;
[cqlsh 5.0.1 | Cassandra 3.11.10 | CQL spec 3.4.4 | Native protocol v4]
```

**Comment by nwheeler81** [comment]
@zencircle but it looks like you have an error when activated py37
...
```
[root@centos ~]# conda activate py37
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>
```
...

**Comment by zencircle** [comment]
Using spark row estimator as a an alternative, closing
